export enum MatchInference {

  HOME_DOMINATING = "HOME_DOMINATING",

  AWAY_DOMINATING = "AWAY_DOMINATING",

  MATCH_BALANCED = "MATCH_BALANCED",

  PRESSURE_RISING = "PRESSURE_RISING",

  PRESSURE_FALLING = "PRESSURE_FALLING",

  MOMENTUM_HOME = "MOMENTUM_HOME",

  MOMENTUM_AWAY = "MOMENTUM_AWAY",

  GOAL_PROBABILITY_HIGH = "GOAL_PROBABILITY_HIGH",

  MARKET_DELAY = "MARKET_DELAY"

}